CREATE TABLE IF NOT EXISTS CentralProcessingUnits
(
    hostID                      BIGINT UNSIGNED         NOT NULL,
    processorNumber             TINYINT UNSIGNED        NOT NULL,
    vendorID                    VARCHAR(12)             NULL,
    cpuFamily                   TINYINT UNSIGNED        NULL, -- I cannot find any documentation of this anywhere. Even in the Intel documentation itself, https://superuser.com/questions/1154244/what-is-cpu-family.
    model                       TINYINT UNSIGNED        NULL,
    modelName                   VARCHAR(64)             NULL, -- Returned in a complicated way from cpuid.c
    stepping                    TINYINT UNSIGNED        NULL,
    cpuMegahertz                FLOAT UNSIGNED          NULL,
    cacheSizeInKilobytes        SMALLINT UNSIGNED       NULL,
    physicalID                  TINYINT UNSIGNED        NULL,
    siblings                    TINYINT UNSIGNED        NULL,
    coreID                      TINYINT UNSIGNED        NULL,
    cpuCores                    TINYINT UNSIGNED        NULL,
    apicID                      TINYINT UNSIGNED        NULL,
    initialAPICID               TINYINT UNSIGNED        NULL,
    hasFloatingPointUnit        BOOLEAN                 NULL,
    floatingPointUnitException  BOOLEAN                 NULL, -- I don't know what this means, nor can I find any information.
    cpuidLevel                  TINYINT UNSIGNED        NULL,
    wp                          BOOLEAN                 NULL, -- There is no documentation whatsoever on what this means. Not even in the Linux source.
    bogoMIPS                    FLOAT UNSIGNED          NULL,
    cacheLineFlushSize          TINYINT UNSIGNED        NULL,
    cacheAlignment              TINYINT UNSIGNED        NULL,
    physicalAddressSize         TINYINT UNSIGNED        NULL,
    virtualAddressSize          TINYINT UNSIGNED        NULL,

    -- CPU Flags
    -- Source: https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux-stable.git/tree/arch/x86/include/asm/cpufeatures.h?id=refs/tags/v4.9
    fpu                         BOOLEAN                 NULL,
    vme                         BOOLEAN                 NULL,
    de                          BOOLEAN                 NULL,
    pse                         BOOLEAN                 NULL,
    tsc                         BOOLEAN                 NULL,
    msr                         BOOLEAN                 NULL,
    pae                         BOOLEAN                 NULL,
    mce                         BOOLEAN                 NULL,
    cx8                         BOOLEAN                 NULL,
    apic                        BOOLEAN                 NULL,
    sep                         BOOLEAN                 NULL,
    mtrr                        BOOLEAN                 NULL,
    pge                         BOOLEAN                 NULL,
    mca                         BOOLEAN                 NULL,
    cmov                        BOOLEAN                 NULL,
    pat                         BOOLEAN                 NULL,
    pse36                       BOOLEAN                 NULL,
    pn                          BOOLEAN                 NULL,
    clflush                     BOOLEAN                 NULL,
    ds                          BOOLEAN                 NULL,
    acpi                        BOOLEAN                 NULL,
    mmx                         BOOLEAN                 NULL,
    fxsr                        BOOLEAN                 NULL,
    xmm                         BOOLEAN                 NULL,
    xmm2                        BOOLEAN                 NULL,
    selfsnoop                   BOOLEAN                 NULL,
    ht                          BOOLEAN                 NULL,
    acc                         BOOLEAN                 NULL,
    ia64                        BOOLEAN                 NULL,
    pbe                         BOOLEAN                 NULL,
    syscall                     BOOLEAN                 NULL,
    mp                          BOOLEAN                 NULL,
    nx                          BOOLEAN                 NULL,
    mmxext                      BOOLEAN                 NULL,
    fxsr_opt                    BOOLEAN                 NULL,
    gbpages                     BOOLEAN                 NULL,
    rdtscp                      BOOLEAN                 NULL,
    lm                          BOOLEAN                 NULL,
    3dnowext                    BOOLEAN                 NULL,
    3dnow                       BOOLEAN                 NULL,
    recovery                    BOOLEAN                 NULL,
    longrun                     BOOLEAN                 NULL,
    lrti                        BOOLEAN                 NULL,
    cxmmx                       BOOLEAN                 NULL,
    k6_mtrr                     BOOLEAN                 NULL,
    cyrix_arr                   BOOLEAN                 NULL,
    centaur_mcr                 BOOLEAN                 NULL,
    k8                          BOOLEAN                 NULL,
    k7                          BOOLEAN                 NULL,
    p3                          BOOLEAN                 NULL,
    p4                          BOOLEAN                 NULL,
    constant_tsc                BOOLEAN                 NULL,
    up                          BOOLEAN                 NULL,
    art                         BOOLEAN                 NULL,
    arch_perfmon                BOOLEAN                 NULL,
    pebs                        BOOLEAN                 NULL,
    bts                         BOOLEAN                 NULL,
    syscall32                   BOOLEAN                 NULL,
    sysenter32                  BOOLEAN                 NULL,
    rep_good                    BOOLEAN                 NULL,
    mfence_rdtsc                BOOLEAN                 NULL,
    lfence_rdtsc                BOOLEAN                 NULL,
    acc_power                   BOOLEAN                 NULL,
    nopl                        BOOLEAN                 NULL,
    always                      BOOLEAN                 NULL,
    xtopology                   BOOLEAN                 NULL,
    tsc_reliable                BOOLEAN                 NULL,
    nonstop_tsc                 BOOLEAN                 NULL,
    extd_apicid                 BOOLEAN                 NULL,
    amd_dcm                     BOOLEAN                 NULL,
    aperfmperf                  BOOLEAN                 NULL,
    eager_fpu                   BOOLEAN                 NULL,
    nonstop_tsc_s3              BOOLEAN                 NULL,
    xmm3                        BOOLEAN                 NULL,
    pclmulqdq                   BOOLEAN                 NULL,
    dtes64                      BOOLEAN                 NULL,
    mwait                       BOOLEAN                 NULL,
    dscpl                       BOOLEAN                 NULL,
    vmx                         BOOLEAN                 NULL,
    smx                         BOOLEAN                 NULL,
    est                         BOOLEAN                 NULL,
    tm2                         BOOLEAN                 NULL,
    ssse3                       BOOLEAN                 NULL,
    cid                         BOOLEAN                 NULL,
    sdbg                        BOOLEAN                 NULL,
    fma                         BOOLEAN                 NULL,
    cx16                        BOOLEAN                 NULL,
    xtpr                        BOOLEAN                 NULL,
    pdcm                        BOOLEAN                 NULL,
    pcid                        BOOLEAN                 NULL,
    dca                         BOOLEAN                 NULL,
    xmm4_1                      BOOLEAN                 NULL,
    xmm4_2                      BOOLEAN                 NULL,
    x2apic                      BOOLEAN                 NULL,
    movbe                       BOOLEAN                 NULL,
    popcnt                      BOOLEAN                 NULL,
    tsc_deadline_timer          BOOLEAN                 NULL,
    aes                         BOOLEAN                 NULL,
    xsave                       BOOLEAN                 NULL,
    osxsave                     BOOLEAN                 NULL,
    avx                         BOOLEAN                 NULL,
    f16c                        BOOLEAN                 NULL,
    rdrand                      BOOLEAN                 NULL,
    hypervisor                  BOOLEAN                 NULL,
    xstore                      BOOLEAN                 NULL,
    xstore_en                   BOOLEAN                 NULL,
    xcrypt                      BOOLEAN                 NULL,
    xcrypt_en                   BOOLEAN                 NULL,
    ace2                        BOOLEAN                 NULL,
    ace2_en                     BOOLEAN                 NULL,
    phe                         BOOLEAN                 NULL,
    phe_en                      BOOLEAN                 NULL,
    pmm                         BOOLEAN                 NULL,
    pmm_en                      BOOLEAN                 NULL,
    lahf_lm                     BOOLEAN                 NULL,
    cmp_legacy                  BOOLEAN                 NULL,
    svm                         BOOLEAN                 NULL,
    extapic                     BOOLEAN                 NULL,
    cr8_legacy                  BOOLEAN                 NULL,
    abm                         BOOLEAN                 NULL,
    sse4a                       BOOLEAN                 NULL,
    misalignsse                 BOOLEAN                 NULL,
    3dnowprefetch               BOOLEAN                 NULL,
    osvw                        BOOLEAN                 NULL,
    ibs                         BOOLEAN                 NULL,
    xop                         BOOLEAN                 NULL,
    skinit                      BOOLEAN                 NULL,
    wdt                         BOOLEAN                 NULL,
    lwp                         BOOLEAN                 NULL,
    fma4                        BOOLEAN                 NULL,
    tce                         BOOLEAN                 NULL,
    nodeid_msr                  BOOLEAN                 NULL,
    tbm                         BOOLEAN                 NULL,
    topoext                     BOOLEAN                 NULL,
    perfctr_core                BOOLEAN                 NULL,
    perfctr_nb                  BOOLEAN                 NULL,
    bpext                       BOOLEAN                 NULL,
    ptsc                        BOOLEAN                 NULL,
    perfctr_l2                  BOOLEAN                 NULL,
    mwaitx                      BOOLEAN                 NULL,
    cpb                         BOOLEAN                 NULL,
    epb                         BOOLEAN                 NULL,
    hw_pstate                   BOOLEAN                 NULL,
    proc_feedback               BOOLEAN                 NULL,
    intel_pt                    BOOLEAN                 NULL,
    avx512_4vnniw               BOOLEAN                 NULL,
    avx512_4fmaps               BOOLEAN                 NULL,
    tpr_shadow                  BOOLEAN                 NULL,
    vnmi                        BOOLEAN                 NULL,
    flexpriority                BOOLEAN                 NULL,
    ept                         BOOLEAN                 NULL,
    vpid                        BOOLEAN                 NULL,
    vmmcall                     BOOLEAN                 NULL,
    xenpv                       BOOLEAN                 NULL,
    fsgsbase                    BOOLEAN                 NULL,
    tsc_adjust                  BOOLEAN                 NULL,
    bmi1                        BOOLEAN                 NULL,
    hle                         BOOLEAN                 NULL,
    avx2                        BOOLEAN                 NULL,
    smep                        BOOLEAN                 NULL,
    bmi2                        BOOLEAN                 NULL,
    erms                        BOOLEAN                 NULL,
    invpcid                     BOOLEAN                 NULL,
    rtm                         BOOLEAN                 NULL,
    cqm                         BOOLEAN                 NULL,
    mpx                         BOOLEAN                 NULL,
    avx512f                     BOOLEAN                 NULL,
    avx512dq                    BOOLEAN                 NULL,
    rdseed                      BOOLEAN                 NULL,
    adx                         BOOLEAN                 NULL,
    smap                        BOOLEAN                 NULL,
    clflushopt                  BOOLEAN                 NULL,
    clwb                        BOOLEAN                 NULL,
    avx512pf                    BOOLEAN                 NULL,
    avx512er                    BOOLEAN                 NULL,
    avx512cd                    BOOLEAN                 NULL,
    sha_ni                      BOOLEAN                 NULL,
    avx512bw                    BOOLEAN                 NULL,
    avx512vl                    BOOLEAN                 NULL,
    xsaveopt                    BOOLEAN                 NULL,
    xsavec                      BOOLEAN                 NULL,
    xgetbv1                     BOOLEAN                 NULL,
    xsaves                      BOOLEAN                 NULL,
    cqm_llc                     BOOLEAN                 NULL,
    cqm_occup_llc               BOOLEAN                 NULL,
    cqm_mbm_total               BOOLEAN                 NULL,
    cqm_mbm_local               BOOLEAN                 NULL,
    clzero                      BOOLEAN                 NULL,
    irperf                      BOOLEAN                 NULL,
    dtherm                      BOOLEAN                 NULL,
    ida                         BOOLEAN                 NULL,
    arat                        BOOLEAN                 NULL,
    pln                         BOOLEAN                 NULL,
    pts                         BOOLEAN                 NULL,
    hwp                         BOOLEAN                 NULL,
    hwp_notify                  BOOLEAN                 NULL,
    hwp_act_window              BOOLEAN                 NULL,
    hwp_epp                     BOOLEAN                 NULL,
    hwp_pkg_req                 BOOLEAN                 NULL,
    npt                         BOOLEAN                 NULL,
    lbrv                        BOOLEAN                 NULL,
    svml                        BOOLEAN                 NULL,
    nrips                       BOOLEAN                 NULL,
    tscratemsr                  BOOLEAN                 NULL,
    vmcbclean                   BOOLEAN                 NULL,
    flushbyasid                 BOOLEAN                 NULL,
    decodeassists               BOOLEAN                 NULL,
    pausefilter                 BOOLEAN                 NULL,
    pfthreshold                 BOOLEAN                 NULL,
    avic                        BOOLEAN                 NULL,
    pku                         BOOLEAN                 NULL,
    ospke                       BOOLEAN                 NULL,
    overflow_recov              BOOLEAN                 NULL,
    succor                      BOOLEAN                 NULL,
    smca                        BOOLEAN                 NULL,

    -- Bugs
    f00f                        BOOLEAN                 NULL,
    fdiv                        BOOLEAN                 NULL,
    coma                        BOOLEAN                 NULL,
    amd_tlb_mmatch              BOOLEAN                 NULL,
    amd_apic_c1e                BOOLEAN                 NULL,
    11ap                        BOOLEAN                 NULL,
    fxsave_leak                 BOOLEAN                 NULL,
    clflush_monitor             BOOLEAN                 NULL,
    sysret_ss_attrs             BOOLEAN                 NULL,
    espfix                      BOOLEAN                 NULL,
    null_seg                    BOOLEAN                 NULL,
    swapgs_fence                BOOLEAN                 NULL,
    monitor                     BOOLEAN                 NULL,
    cpu_meltdown                BOOLEAN                 NULL,
    spectre_v1                  BOOLEAN                 NULL,
    spectre_v2                  BOOLEAN                 NULL,

    FOREIGN KEY (hostID) REFERENCES Hosts (id),
    PRIMARY KEY (hostID, processorNumber)
);

-- NOTE:
-- I did find this note about cpuFamily:
-- "Authoritatively identifies the type of processor in the system. For an
-- Intel-based system, place the number in front of "86" to determine the
-- value. This is particularly helpful for those attempting to identify the
-- architecture of an older system such as a 586, 486, or 386. Because some
-- RPM packages are compiled for each of these particular architectures, this
-- value also helps users determine which packages to install."